version: '3.8'

services:
  springboot-app:
    image: openjdk:17-jdk-slim
    container_name: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - kafka
      - elasticsearch
    environment:
      SPRING_PROFILES_ACTIVE: prd

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mySecretPassword123
      MYSQL_DATABASE: foursales_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_secret
    ports:
      - "3306:3306"
    volumes:
      - .data/mysql:/var/lib/mysql

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - .data/zookeeper:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_DOCKER://kafka:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_DOCKER://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_DOCKER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - .data/kafka:/bitnami/kafka
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8081:8080"
    restart: always
    environment:
      # - DYNAMIC_CONFIG_ENABLED=true
      - SPRING_CONFIG_ADDITIONAL-LOCATION= /config.yml
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    volumes:
      - .data/kafka-ui/config.yml:/config.yml
    depends_on:
      - kafka
      - zookeeper

  elasticsearch:
    image: bitnami/elasticsearch:latest
    container_name: elasticsearch
    environment:
      - ELASTICSEARCH_NODE_NAME=elasticsearch
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_NETWORK_HOST=0.0.0.0
      - ELASTICSEARCH_HTTP_PORT=9200
      - ELASTICSEARCH_DISCOVERY_TYPE=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - .data/elasticsearch:/bitnami/elasticsearch

  kibana:
    image: bitnami/kibana:latest
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      KIBANA_ELASTICSEARCH_URL: elasticsearch
    depends_on:
      - elasticsearch
